# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85e01d2ee29cbe3268fd103b4865c62d54e915c8525bc77e2f482704481651a196ff5031aac352425295cb1cfbaa4349744f940ee6154acd82d94d734f9362d3

test:
  secret_key_base: 469736ce802878dc347f821d1de04ea3904672a2fee65c0349b4631879c122f5f84a172548e5c927a8690a5ff145a74bf4dc6451ae5d0508404bf4c9f592dd0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
